#!/bin/bash
while true
do
	touch /tmp/fastlog
	
	echo "Running Bandwith test..."
    
	/usr/src/app/node_modules/.bin/fast --upload --single-line | tail -n 1 > /tmp/fastlog

	echo "Bandwith test finished."
	
	cat /tmp/fastlog

	DOWN=$(cat /tmp/fastlog | cut -d' ' -f5)
	UP=$(cat /tmp/fastlog | cut -d' ' -f9)

	if [[ -z "${MQTT_PASS}" ]]; then
	echo "Sending Data to MQTT ($MQTT_SERVER)"
		mosquitto_pub -u $MQTT_USER -P $MQTT_PASS -h $MQTT_SERVER -t $MQTT_DOWN -m $DOWN
		mosquitto_pub -u $MQTT_USER -P $MQTT_PASS -h $MQTT_SERVER -t $MQTT_UP -m $UP
	else
	echo "Sending Data to MQTT ($MQTT_SERVER) -  No Auth"
		mosquitto_pub -h $MQTT_SERVER -t $MQTT_DOWN -m $DOWN
		mosquitto_pub -h $MQTT_SERVER -t $MQTT_UP -m $UP
	fi 

	echo "Waiting for $SLEEP Seconds to continue..."
	
	sleep $SLEEP 

done